In [92]:
import numpy as np
import pandas as pd 
import matplotlib as mlt
import seaborn as sns

In [93]:
df = pd.read_csv("Listings.csv", encoding="latin1")

C:\Users\sabba\AppData\Local\Temp\ipykernel_143200\1630855267.py:1: DtypeWarning: Columns (0: host_response_time, 1: district) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Listings.csv", encoding="latin1")

In [94]:
df.sample(5)

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,district,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,amenities,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
269804,461860,Lovely Apartment in Montmartre,2295636,2012-05-05,"Paris, Ile-de-France, France",within a day,1.0,0.6,f,1.0,t,t,Buttes-Montmartre,NaN,Paris,48.88818,2.33505,Entire apartment,Entire place,4,1.0,"[""Paid parking off premises"", ""Shampoo"", ""Dish...",80,2,60,91.0,9.0,8.0,10.0,10.0,10.0,9.0,f
250050,10098646,Loft con soppalco vicino Piazza Navona,8024792,2013-08-08,"Rome, Lazio, Italy",within a few hours,1.0,1.0,t,3.0,t,t,I Centro Storico,NaN,Rome,41.90031,12.46950,Entire apartment,Entire place,4,1.0,"[""Pack \u2019n Play/travel crib"", ""Crib"", ""Bat...",98,2,29,99.0,10.0,10.0,10.0,10.0,10.0,10.0,t
247959,24481344,Appartement familial ÃÂ Saint-Germain des Pres,184552317,2018-04-16,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,0.0,t,t,Luxembourg,NaN,Paris,48.84659,2.32457,Entire apartment,Entire place,4,3.0,"[""Dishwasher"", ""Essentials"", ""Stove"", ""Hot wat...",165,3,14,98.0,10.0,10.0,10.0,10.0,10.0,10.0,f
245126,41353422,Ã¥ÅÂ°Ã©âÂÃ¥ÂÂ£ Ã§Â¦ÂÃ§âÂ°Ã¤Â¸Â­Ã¥Â¿Æ ...,230444430,2018-12-13,China,within an hour,1.0,1.0,t,6.0,t,t,North,NaN,Hong Kong,22.53230,114.08634,Entire apartment,Entire place,2,1.0,"[""Shampoo"", ""Bed linens"", ""Hair dryer"", ""Long ...",405,2,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t
233557,38878986,Vila de Noel,297746986,2019-09-24,BR,NaN,NaN,NaN,f,0.0,t,f,Vila Isabel,NaN,Rio de Janeiro,-22.91341,-43.24702,Entire apartment,Entire place,3,1.0,"[""Elevator"", ""Kitchen"", ""Washer"", ""Long term s...",150,7,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t

shape of data

In [95]:
df.shape

(279712, 33)

data type of data

In [96]:
df.info

<bound method DataFrame.info of         listing_id                                               name  \
0           281420     Beautiful Flat in le Village Montmartre, Paris
1          3705183                    39 mÃÂ² Paris (Sacre CÃ
âur)
2          4082273                Lovely apartment with Terrace, 60m2
3          4797344                Cosy studio (close to Eiffel tower)
4          4823489   Close to Eiffel Tower - Beautiful flat : 2 rooms
...            ...                                                ...
279707    38338635  Appartement T2 neuf prÃÂ¨s du tram T3a Porte ...
279708    38538692                          Cozy Studio in Montmartre
279709    38683356            Nice and cosy mini-appartement in Paris
279710    39659000  Charming apartment near Rue Saint Maur / Oberk...
279711    40219504        Cosy apartment with view on Canal St Martin

         host_id  host_since                 host_location host_response_time  \
0        1466919  2011-12-03  Paris, Ile-de-France, France                NaN
1       10328771  2013-11-29  Paris, Ile-de-France, France                NaN
2       19252768  2014-07-31  Paris, Ile-de-France, France                NaN
3       10668311  2013-12-17  Paris, Ile-de-France, France                NaN
4       24837558  2014-12-14  Paris, Ile-de-France, France                NaN
...          ...         ...                           ...                ...
279707  31161181  2015-04-13  Paris, Ile-de-France, France                NaN
279708  10294858  2013-11-27  Paris, Ile-de-France, France                NaN
279709   2238502  2012-04-27  Paris, Ile-de-France, France                NaN
279710  38633695  2015-07-16  Paris, Ile-de-France, France                NaN
279711   6955618  2013-06-17  Paris, Ile-de-France, France                NaN

        host_response_rate  host_acceptance_rate host_is_superhost  \
0                      NaN                   NaN                 f
1                      NaN                   NaN                 f
2                      NaN                   NaN                 f
3                      NaN                   NaN                 f
4                      NaN                   NaN                 f
...                    ...                   ...               ...
279707                 NaN                   NaN                 f
279708                 NaN                   NaN                 f
279709                 NaN                   NaN                 f
279710                 NaN                   NaN                 f
279711                 NaN                   NaN                 f

        host_total_listings_count host_has_profile_pic host_identity_verified  \
0                             1.0                    t                      f
1                             1.0                    t                      t
2                             1.0                    t                      f
3                             1.0                    t                      t
4                             1.0                    t                      f
...                           ...                  ...                    ...
279707                        1.0                    t                      t
279708                        1.0                    t                      t
279709                        1.0                    t                      t
279710                        1.0                    t                      t
279711                        1.0                    t                      t

            neighbourhood district   city  latitude  longitude  \
0       Buttes-Montmartre      NaN  Paris  48.88668    2.33343
1       Buttes-Montmartre      NaN  Paris  48.88617    2.34515
2                  Elysee      NaN  Paris  48.88112    2.31712
3               Vaugirard      NaN  Paris  48.84571    2.30584
4                   Passy      NaN  Paris  48.85500    2.26979
...                   ...      ...    ...       ...        ...
279707       Observatoire      NaN  Paris  48.82701    2.31419
279708  Buttes-Montmartre      NaN  Paris  48.89309    2.33206
279709  Buttes-Montmartre      NaN  Paris  48.88699    2.34920
279710         Popincourt      NaN  Paris  48.86687    2.38123
279711  Enclos-St-Laurent      NaN  Paris  48.87217    2.36320

           property_type     room_type  accommodates  bedrooms  \
0       Entire apartment  Entire place             2       1.0
1       Entire apartment  Entire place             2       1.0
2       Entire apartment  Entire place             2       1.0
3       Entire apartment  Entire place             2       1.0
4       Entire apartment  Entire place             2       1.0
...                  ...           ...           ...       ...
279707  Entire apartment  Entire place             2       1.0
279708  Entire apartment  Entire place             2       1.0
279709  Entire apartment  Entire place             2       1.0
279710  Entire apartment  Entire place             2       1.0
279711  Entire apartment  Entire place             2       1.0

                                                amenities  price  \
0       ["Heating", "Kitchen", "Washer", "Wifi", "Long...     53
1       ["Shampoo", "Heating", "Kitchen", "Essentials"...    120
2       ["Heating", "TV", "Kitchen", "Washer", "Wifi",...     89
3       ["Heating", "TV", "Kitchen", "Wifi", "Long ter...     58
4       ["Heating", "TV", "Kitchen", "Essentials", "Ha...     60
...                                                   ...    ...
279707  ["Iron", "Heating", "Washer", "Dedicated works...    120
279708  ["Shampoo", "Iron", "Heating", "Washer", "Hair...     60
279709  ["Paid parking off premises", "Shampoo", "Firs...     50
279710  ["TV", "Iron", "Kitchen", "Hangers", "Smoke al...    105
279711  ["Shower gel", "Shampoo", "Iron", "Heating", "...     70

        minimum_nights  maximum_nights  review_scores_rating  \
0                    2            1125                 100.0
1                    2            1125                 100.0
2                    2            1125                 100.0
3                    2            1125                 100.0
4                    2            1125                 100.0
...                ...             ...                   ...
279707               1               7                 100.0
279708               7              15                 100.0
279709               6              30                 100.0
279710               3              18                 100.0
279711               2               4                 100.0

        review_scores_accuracy  review_scores_cleanliness  \
0                         10.0                       10.0
1                         10.0                       10.0
2                         10.0                       10.0
3                         10.0                       10.0
4                         10.0                       10.0
...                        ...                        ...
279707                    10.0                       10.0
279708                    10.0                       10.0
279709                    10.0                       10.0
279710                    10.0                       10.0
279711                    10.0                       10.0

        review_scores_checkin  review_scores_communication  \
0                        10.0                         10.0
1                        10.0                         10.0
2                        10.0                         10.0
3                        10.0                         10.0
4                        10.0                         10.0
...                       ...                          ...
279707                   10.0                         10.0
279708                   10.0                         10.0
279709                   10.0                         10.0
279710                   10.0                         10.0
279711                   10.0                         10.0

        review_scores_location  review_scores_value instant_bookable
0                         10.0                 10.0                f
1                         10.0                 10.0                f
2                         10.0                 10.0                f
3                         10.0                 10.0                f
4                         10.0                 10.0                f
...                        ...                  ...              ...
279707                    10.0                 10.0                f
279708                    10.0                 10.0                f
279709                    10.0                 10.0                f
279710                    10.0                 10.0                f
279711                    10.0                 10.0                f

[279712 rows x 33 columns]>

missing values

In [97]:
df.isna().sum()

listing_id                          0
name                              175
host_id                             0
host_since                        165
host_location                     840
host_response_time             128782
host_response_rate             128782
host_acceptance_rate           113087
host_is_superhost                 165
host_total_listings_count         165
host_has_profile_pic              165
host_identity_verified            165
neighbourhood                       0
district                       242700
city                                0
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bedrooms                        29435
amenities                           0
price                               0
minimum_nights                      0
maximum_nights                      0
review_scores_rating            91405
review_scores_accuracy          91713
review_scores_cleanliness       91665
review_scores_checkin           91771
review_scores_communication     91687
review_scores_location          91775
review_scores_value             91785
instant_bookable                    0
dtype: int64

how does the data look mathematicaly

In [98]:
df.describe()

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
count,2.797120e+05,2.797120e+05,150930.000000,166625.000000,279547.000000,279712.000000,279712.000000,279712.000000,250277.000000,279712.000000,279712.000000,2.797120e+05,188307.000000,187999.000000,188047.000000,187941.000000,188025.000000,187937.000000,187927.000000
mean,2.638196e+07,1.081658e+08,0.865939,0.827168,24.581612,18.761862,12.595075,3.288736,1.515509,608.792737,8.050967,2.755860e+04,93.405195,9.565476,9.312869,9.701534,9.698593,9.633994,9.335364
std,1.442576e+07,1.108570e+08,0.283744,0.289202,284.041143,32.560343,73.081309,2.133379,1.153080,3441.826611,31.518946,7.282875e+06,10.070437,0.990878,1.146072,0.867434,0.886884,0.833234,1.042625
min,2.577000e+03,1.822000e+03,0.000000,0.000000,0.000000,-34.264400,-99.339630,0.000000,1.000000,0.000000,1.000000,1.000000e+00,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
25%,1.384462e+07,1.720656e+07,0.900000,0.780000,1.000000,-22.964390,-43.198040,2.000000,1.000000,75.000000,1.000000,4.500000e+01,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000
50%,2.767098e+07,5.826911e+07,1.000000,0.980000,1.000000,40.710785,2.382780,2.000000,1.000000,150.000000,2.000000,1.125000e+03,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
75%,3.978485e+07,1.832853e+08,1.000000,1.000000,4.000000,41.908610,28.986730,4.000000,2.000000,474.000000,5.000000,1.125000e+03,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
max,4.834353e+07,3.901874e+08,1.000000,1.000000,7235.000000,48.904910,151.339810,16.000000,50.000000,625216.000000,9999.000000,2.147484e+09,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

duplicate

In [99]:
df.duplicated().sum()

np.int64(0)

how is the correlation between cols

In [100]:
df.corr(numeric_only=True)

,listing_id,host_id,host_response_rate,host_acceptance_rate,host_total_listings_count,latitude,longitude,accommodates,bedrooms,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
listing_id,1.000000,0.582679,-0.014195,0.109949,0.071972,-0.012022,-0.001949,-0.005969,0.006881,0.011471,-0.034967,-0.005873,-0.026382,-0.047476,-0.025831,-0.065647,-0.067393,0.016243,-0.020410
host_id,0.582679,1.000000,-0.082474,0.122923,0.015198,0.005266,0.008961,-0.014839,-0.001526,0.011795,-0.038348,-0.003148,-0.089288,-0.095226,-0.055538,-0.100904,-0.103973,-0.046701,-0.067068
host_response_rate,-0.014195,-0.082474,1.000000,0.321510,0.037986,-0.015872,-0.018426,0.012068,-0.007806,-0.000697,-0.012630,0.000048,0.112409,0.108358,0.118284,0.106289,0.120641,0.091927,0.099234
host_acceptance_rate,0.109949,0.122923,0.321510,1.000000,0.034085,0.073135,-0.003525,-0.008704,-0.045264,-0.039315,-0.045547,0.000307,-0.017294,-0.007801,0.028197,-0.013868,-0.011385,0.005349,0.000529
host_total_listings_count,0.071972,0.015198,0.037986,0.034085,1.000000,-0.042281,0.061737,-0.018868,-0.009910,0.009907,-0.000161,-0.000303,-0.037162,-0.040658,-0.016856,-0.036414,-0.045739,-0.005259,-0.049027
latitude,-0.012022,0.005266,-0.015872,0.073135,-0.042281,1.000000,-0.417783,-0.111880,-0.137463,-0.099278,0.046801,0.001569,-0.034199,-0.007049,-0.035079,-0.023368,-0.011368,-0.043589,-0.022222
longitude,-0.001949,0.008961,-0.018426,-0.003525,0.061737,-0.417783,1.000000,0.009465,0.037800,0.019608,-0.056316,-0.001410,-0.048905,-0.052181,-0.045029,-0.043660,-0.033794,-0.052074,-0.039725
accommodates,-0.005969,-0.014839,0.012068,-0.008704,-0.018868,-0.111880,0.009465,1.000000,0.639102,0.146327,-0.033442,0.003241,0.006420,-0.009308,0.007203,0.004743,-0.000910,0.008774,-0.023706
bedrooms,0.006881,-0.001526,-0.007806,-0.045264,-0.009910,-0.137463,0.037800,0.639102,1.000000,0.143307,-0.010582,0.000872,0.009007,-0.010811,0.002247,0.005562,-0.004753,0.008412,-0.019745
price,0.011471,0.011795,-0.000697,-0.039315,0.009907,-0.099278,0.019608,0.146327,0.143307,1.000000,0.006344,-0.000442,0.015048,-0.000693,0.024328,-0.000243,-0.003262,-0.000609,0.001572
minimum_nights,-0.034967,-0.038348,-0.012630,-0.045547,-0.000161,0.046801,-0.056316,-0.033442,-0.010582,0.006344,1.000000,0.000248,0.000143,-0.000529,-0.013915,-0.001112,-0.001204,-0.008982,-0.004731
maximum_nights,-0.005873,-0.003148,0.000048,0.000307,-0.000303,0.001569,-0.001410,0.003241,0.000872,-0.000442,0.000248,1.000000,-0.002795,-0.003251,-0.002943,-0.002934,-0.002895,0.000397,-0.003954
review_scores_rating,-0.026382,-0.089288,0.112409,-0.017294,-0.037162,-0.034199,-0.048905,0.006420,0.009007,0.015048,0.000143,-0.002795,1.000000,0.785838,0.740594,0.661642,0.709482,0.540717,0.782864
review_scores_accuracy,-0.047476,-0.095226,0.108358,-0.007801,-0.040658,-0.007049,-0.052181,-0.009308,-0.010811,-0.000693,-0.000529,-0.003251,0.785838,1.000000,0.647809,0.655795,0.682926,0.532866,0.717447
review_scores_cleanliness,-0.025831,-0.055538,0.118284,0.028197,-0.016856,-0.035079,-0.045029,0.007203,0.002247,0.024328,-0.013915,-0.002943,0.740594,0.647809,1.000000,0.525337,0.540806,0.430433,0.654149
review_scores_checkin,-0.065647,-0.100904,0.106289,-0.013868,-0.036414,-0.023368,-0.043660,0.004743,0.005562,-0.000243,-0.001112,-0.002934,0.661642,0.655795,0.525337,1.000000,0.736436,0.519118,0.595167
review_scores_communication,-0.067393,-0.103973,0.120641,-0.011385,-0.045739,-0.011368,-0.033794,-0.000910,-0.004753,-0.003262,-0.001204,-0.002895,0.709482,0.682926,0.540806,0.736436,1.000000,0.520654,0.634834
review_scores_location,0.016243,-0.046701,0.091927,0.005349,-0.005259,-0.043589,-0.052074,0.008774,0.008412,-0.000609,-0.008982,0.000397,0.540717,0.532866,0.430433,0.519118,0.520654,1.000000,0.532644
review_scores_value,-0.020410,-0.067068,0.099234,0.000529,-0.049027,-0.022222,-0.039725,-0.023706,-0.019745,0.001572,-0.004731,-0.003954,0.782864,0.717447,0.654149,0.595167,0.634834,0.532644,1.000000

In [101]:
df['name'] = df['name'].fillna('Unknown')
df['name']

0            Beautiful Flat in le Village Montmartre, Paris
1                           39 mÃÂ² Paris (Sacre CÃ
âur)
2                       Lovely apartment with Terrace, 60m2
3                       Cosy studio (close to Eiffel tower)
4          Close to Eiffel Tower - Beautiful flat : 2 rooms
                                ...
279707    Appartement T2 neuf prÃÂ¨s du tram T3a Porte ...
279708                            Cozy Studio in Montmartre
279709              Nice and cosy mini-appartement in Paris
279710    Charming apartment near Rue Saint Maur / Oberk...
279711          Cosy apartment with view on Canal St Martin
Name: name, Length: 279712, dtype: str

In [103]:
df['host_since'] = df['host_since'].ffill()

In [104]:
df['host_location'] = df['host_location'].ffill()

In [105]:
df['host_response_time'] = df['host_response_time'].ffill()

In [106]:
df['host_response_time'] = df['host_response_time'].fillna("within an hour")

In [107]:
df['host_response_rate'] = df['host_response_rate'].fillna(1)

In [108]:
df['host_acceptance_rate'] = df['host_acceptance_rate'].ffill()

In [109]:
df['host_acceptance_rate'] = df['host_acceptance_rate'].fillna(1)

In [110]:
df['host_is_superhost'] = df['host_is_superhost'].ffill()

In [111]:
df['host_total_listings_count'] = df['host_total_listings_count'].ffill()

In [112]:
df['host_has_profile_pic'] = df['host_has_profile_pic'].ffill()

In [116]:
df['host_identity_verified'] = df['host_identity_verified'].ffill()

In [ ]:
pd.set_option('display.max_columns', None)

In [118]:
df['bedrooms'] = df['bedrooms'].ffill()

In [122]:
df['review_scores_communication'] = df['review_scores_communication'].ffill()
df['review_scores_location'] = df['review_scores_location'].ffill()
df['review_scores_value'] = df['review_scores_value'].ffill()

In [124]:
df['district'] = df['district'].fillna("unkonwn")

In [121]:
df.head()

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood,district,city,latitude,longitude,property_type,room_type,accommodates,bedrooms,amenities,price,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,1.0,t,f,Buttes-Montmartre,NaN,Paris,48.88668,2.33343,Entire apartment,Entire place,2,1.0,"[""Heating"", ""Kitchen"", ""Washer"", ""Wifi"", ""Long...",53,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,1.0,t,t,Buttes-Montmartre,NaN,Paris,48.88617,2.34515,Entire apartment,Entire place,2,1.0,"[""Shampoo"", ""Heating"", ""Kitchen"", ""Essentials""...",120,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,1.0,t,f,Elysee,NaN,Paris,48.88112,2.31712,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Washer"", ""Wifi"",...",89,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,1.0,t,t,Vaugirard,NaN,Paris,48.84571,2.30584,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Wifi"", ""Long ter...",58,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",within an hour,1.0,1.0,f,1.0,t,f,Passy,NaN,Paris,48.85500,2.26979,Entire apartment,Entire place,2,1.0,"[""Heating"", ""TV"", ""Kitchen"", ""Essentials"", ""Ha...",60,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [ ]:
df.isna().sum()

listing_id                         0
name                               0
host_id                            0
host_since                         0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
neighbourhood                      0
district                           0
city                               0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bedrooms                           0
amenities                          0
price                              0
minimum_nights                     0
maximum_nights                     0
review_scores_rating           91405
review_scores_accuracy         91713
review_scores_cleanliness      91665
review_scores_checkin          91771
review_scores_communication        0
review_scores_location             0
review_scores_value                0
instant_bookable                   0
dtype: int64

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279712 non-null  str
 2   host_id                      279712 non-null  int64
 3   host_since                   279712 non-null  str
 4   host_location                279712 non-null  str
 5   host_response_time           279712 non-null  str
 6   host_response_rate           279712 non-null  float64
 7   host_acceptance_rate         279712 non-null  float64
 8   host_is_superhost            279712 non-null  str
 9   host_total_listings_count    279712 non-null  float64
 10  host_has_profile_pic         279712 non-null  str
 11  host_identity_verified       279712 non-null  str
 12  neighbourhood                279712 non-null  str
 13  district                     279712 non-null  str
 14  city                         279712 non-null  str
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  str
 18  room_type                    279712 non-null  str
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     279712 non-null  float64
 21  amenities                    279712 non-null  str
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  279712 non-null  float64
 30  review_scores_location       279712 non-null  float64
 31  review_scores_value          279712 non-null  float64
 32  instant_bookable             279712 non-null  str
dtypes: float64(13), int64(6), str(14)
memory usage: 70.4 MB

In [127]:
df["host_since"] = pd.to_datetime(df["host_since"])

In [129]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279712 non-null  str
 2   host_id                      279712 non-null  int64
 3   host_since                   279712 non-null  datetime64[us]
 4   host_location                279712 non-null  str
 5   host_response_time           279712 non-null  str
 6   host_response_rate           279712 non-null  float64
 7   host_acceptance_rate         279712 non-null  float64
 8   host_is_superhost            279712 non-null  str
 9   host_total_listings_count    279712 non-null  float64
 10  host_has_profile_pic         279712 non-null  str
 11  host_identity_verified       279712 non-null  str
 12  neighbourhood                279712 non-null  str
 13  district                     279712 non-null  str
 14  city                         279712 non-null  str
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  str
 18  room_type                    279712 non-null  str
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     279712 non-null  float64
 21  amenities                    279712 non-null  str
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  279712 non-null  float64
 30  review_scores_location       279712 non-null  float64
 31  review_scores_value          279712 non-null  float64
 32  instant_bookable             279712 non-null  str
dtypes: datetime64[us](1), float64(13), int64(6), str(13)
memory usage: 70.4 MB